version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
  